import numpy as np

dispositions = [[(9, 2), (8, 8), (4, 5)],
                [(3, 8), (0, 1), (7, 4)],
                [(5, 0), (5, 6), (9, 8)],
                [(8, 0), (1, 3), (6, 7)]]
# probabilty =    [0.7997, 0.0003, 0.1, 0.1]
probabilty =    [0.5, 0.1, 0.2, 0.2]
default_grid =  "r.........\n" + \
                "....x.....\n" + \
                "..........\n" + \
                "x.........\n" + \
                "..x.......\n" + \
                ".........x\n" + \
                "...xxxx...\n" + \
                ".....x...x\n" + \
                "...x...x..\n" + \
                "x...x....x"
length = default_grid.count("\n") + 1
width = (len(default_grid) - length + 1) // 10
dispositionid = np.random.choice(list(range(len(dispositions))), 1, p = probabilty)[0]
dispositionid = 1
"""
First disposition (0.5 probability):
r.........
....x.....
...x......
x.........
..x..T....
.........x
...xxxx...
.....x...x
...x...xT.
x.T.x....x

Second disposition (0.3 probability):
rT........
....x.....
...x......
x.......T.
..x.......
.........x
...xxxx...
....Tx...x
...x...x..
x...x....x

Third disposition (0.1 probability):
r.........
....x.....
...x......
x.........
..x.......
T.....T..x
...xxxx...
.....x...x
...x...x..
x...x...Tx

Fourth disposition (0.1 probability):
r.........
...Tx.....
...x......
x.........
..x.......
.........x
...xxxxT..
.....x...x
T..x...x..
x...x....x
"""