import numpy as np

dispositions = [[(3, 8), (5, 1), (4, 5)],
                [(7, 6), (0, 1), (4, 6)],
                [(0, 6), (5, 6), (9, 8)],
                [(8, 0), (4, 3), (6, 7)]]
probabilty =    [0.2, 0.7, 0.05, 0.05]
default_grid =  "r.........\n" + \
                "....x.....\n" + \
                "......xx..\n" + \
                ".x........\n" + \
                ".xx......x\n" + \
                "..........\n" + \
                ".....x...x\n" + \
                "....xx...x\n" + \
                "..........\n" + \
                "x...xx...x"
length = default_grid.count("\n") + 1
width = (len(default_grid) - length + 1) // 10
dispositionid = np.random.choice(list(range(len(dispositions))), 1, p = probabilty)[0]
#dispositionid = 3
"""
First disposition (0.5 probability):
r.........
....x.....
...x......
x.........
..x..T....
.........x
...xxxx...
.....x...x
...x...xT.
x.T.x....x

Second disposition (0.3 probability):
rT........
....x.....
...x......
x.......T.
..x.......
.........x
...xxxx...
....Tx...x
...x...x..
x...x....x

Third disposition (0.1 probability):
r.........
....x.....
...x......
x.........
..x.......
T.....T..x
...xxxx...
.....x...x
...x...x..
x...x...Tx

Fourth disposition (0.1 probability):
r.........
...Tx.....
...x......
x.........
..x.......
.........x
...xxxxT..
.....x...x
T..x...x..
x...x....x
"""